### ISSUE TITLE
It doesn't work after enabled it (gitea version 1.13.2)

### ISSUE THREAD

**Issue by CornWorld** [FugiMuffi/gitea-dark-green#1]
I installed it in a likely correct way and in ``Edge`` 's development tools' ``Network`` tab can found the css file has already loaded  
But the site's theme doesn't changed anything (I'm sure I had enable it)

The Dir Tree:
![image](https://user-images.githubusercontent.com/43746030/124112084-840b0480-da9c-11eb-9426-aee1871b02b0.png)

The theme selection page:
![image](https://user-images.githubusercontent.com/43746030/124112296-bd437480-da9c-11eb-9848-f7100c39782a.png)

A page with enabled theme:
![image](https://user-images.githubusercontent.com/43746030/124112418-da784300-da9c-11eb-8f78-31595a09a473.png)

Gitea's conf (theme part):
![image](https://user-images.githubusercontent.com/43746030/124112569-0267a680-da9d-11eb-8a48-668fc7ac227b.png)

I tried but nothing changed, could you offer some help?  
If possible, I can give you some permissions (like admin account) to find out why

**Comment by FugiMuffi** [comment]
Your configuration looks right to me. It appears that theme.park (which this theme is based on) have changed their domain on which the base theme css files are hosted. (Even though it does still work for me, oddly enough.)

Can you try changing the two imports at the top of `theme-dark-green.css` to this and see if it works?
```css
/* GITEA ORGANIZR-DARK THEME */
@import url(https://theme-park.dev/CSS/themes/gitea/gitea-base.css);
@import url(https://theme-park.dev/CSS/themes/gitea/chroma.css);
```
Be sure to clear you browser cache after you make the change.

Mind that I only tested this on Gitea 1.13.5 (Docker), while you are on 1.13.2 - though I wouldn't expect it to break because of such a minor version difference.

**Comment by CornWorld** [comment]
Um, it worked
But it doesn't seem to be fully operational

(Forgive me, for not noticing your reply)

![image](https://user-images.githubusercontent.com/43746030/124765278-604a3180-df68-11eb-8854-44a9de931c4a.png)
![image](https://user-images.githubusercontent.com/43746030/124765324-6c35f380-df68-11eb-98b2-2c9ce843f638.png)
![image](https://user-images.githubusercontent.com/43746030/124765387-7c4dd300-df68-11eb-98f8-91fb8bfc3758.png)

**Comment by FugiMuffi** [comment]
Sorry, I don't know what the problem is then. Can you try to install some other theme (e.g. from theme.park) and see if it works? Maybe the problem is somewhere else.

**Comment by CornWorld** [comment]
I download `dark` and `organizr-dark` from theme.park
All of them work

That is a strange situation...


![image](https://user-images.githubusercontent.com/43746030/124834281-0ff7c180-dfb2-11eb-9b05-e7a45792d17f.png)

**Comment by FugiMuffi** [comment]
Is your gitea instance public? Maybe I could take a look if you give me the url

**Comment by CornWorld** [comment]
No, but I will sent to your email

**Comment by CornWorld** [comment]
Is it lucas@fugi.dev?
